<?php
return [
    [
        'id'=>1,
        'slug'=>'first-post',
        'title'=>'First Post',
        'content'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, nisl eget aliquam tincidunt, nunc nisl aliquam nisl, eget aliquam nisl nunc vel nisl. Donec auctor, nisl eget aliquam tincidunt, nunc nisl aliquam nisl, eget aliquam nisl nunc vel nisl.',
        'author'=>'John Doe',
        'published_at'=>'2024-06-01 12:00:00',
        'categories'=>['Laravel','PHP','Programming'],
        'tags'=>['Laravel','PHP','Programming'],
        'image'=>'https://via.placeholder.com/600x400',
    ],
    [
        'id'=>2,
        'slug'=>'second-post',
        'title'=>'Second Post',
        'content'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, nisl eget aliquam tincidunt, nunc nisl aliquam nisl, eget aliquam nisl nunc vel nisl. Donec auctor, nisl eget aliquam tincidunt, nunc nisl aliquam nisl, eget aliquam nisl nunc vel nisl.',
        'author'=>'Jane Doe',
        'published_at'=>'2024-06-02 12:00:00',
        'categories'=>['Laravel','PHP','Programming'],
        'tags'=>['Laravel','PHP','Programming'],
        'image'=>'https://via.placeholder.com/600x400',
    ],
    [
        'id'=>3,
        'slug'=>'third-post',
        'title'=>'Third Post',
        'content'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, nisl eget aliquam tincidunt, nunc nisl aliquam nisl, eget aliquam nisl nunc vel nisl. Donec auctor, nisl eget aliquam tincidunt, nunc nisl aliquam nisl, eget aliquam nisl nunc vel nisl.',
        'author'=>'John Smith',
        'published_at'=>'2024-06-03 12:00:00',
        'categories'=>['Laravel','PHP','Programming'],
        'tags'=>['Laravel','PHP','Programming'],
        'image'=>'https://via.placeholder.com/600x400',
    ],
    [
        'id'=>4,
        'slug'=>'fourth-post',
        'title'=>'Fourth Post',
        'content'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, nisl eget aliquam tincidunt, nunc nisl aliquam nisl, eget aliquam nisl nunc vel nisl. Donec auctor, nisl eget aliquam tincidunt, nunc nisl aliquam nisl, eget aliquam nisl nunc vel nisl.',
        'author'=>'Jane Smith',
        'published_at'=>'2024-06-04 12:00:00',
        'categories'=>['Laravel','PHP','Programming'],
        'tags'=>['Laravel','PHP','Programming'],
        'image'=>'https://via.placeholder.com/600x400',
    ],
    [
        'id'=>5,
        'slug'=>'fifth-post',
        'title'=>'Fifth Post',
        'content'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, nisl eget aliquam tincidunt, nunc nisl aliquam nisl, eget aliquam nisl nunc vel nisl. Donec auctor, nisl eget aliquam tincidunt, nunc nisl aliquam nisl, eget aliquam nisl nunc vel nisl.',
        'author'=>'John Doe',
        'published_at'=>'2024-06-05 12:00:00',
        'categories'=>['Laravel','PHP','Programming'],
        'tags'=>['Laravel','PHP','Programming'],
        'image'=>'https://via.placeholder.com/600x400',
    ],
];